### PR TITLE
v.0.6.0 pre release

### PR DESCRIPTION
**Pull request by lexxai**
v.0.6.0 pre release

### CODE REVIEW

**Comment by OleksaSolo** [comment]
Ok

**Comment by lexxai** [comment]
Ok не достатньо

**Comment by OleksaSolo** [comment]
May be this ...

**Comment by lexxai** [comment]
ні. не це

**Comment by lexxai** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews

**Comment by lexxai** [comment]
image

**Review by OleksaSolo — APPROVED** [review]

**Pull request merged**
